/*
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Authour : Yuvaraj D 
 Total Number of Tables : 34
 created on : 04-Aug-2020
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
CREATE TABLE IF NOT EXISTS CURRENT_USER_DETAILS (
    LAST_MASTER_REFRESH TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_NAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    USER_ID INTEGER NOT NULL,
    IMAGE_URL BLOB,
    ISLOGOUT BOOLEAN,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS LOCAL_NOTIFICATIONS (
    USER_NAME TEXT NOT NULL,
    MSG TEXT NOT NULL,
    DATE_TIME DATE NOT NULL,
    TYPE TEXT NOT NULL
);

/* CREATE TABLE IF NOT EXISTS RESENT_ACTIVITY (ACTIVITY_ID INTEGER NOT NULL, DATE_TIME DATE NOT NULL,USER_ID INTEGER NOT NULL, VESSEL_NAME TEXT NOT NULL,VESSEL_IMO INTEGER NOT NULL, PRIMARY KEY(USER_ID));*/
CREATE TABLE IF NOT EXISTS MA_USERS (
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    PHONE_NO INTEGER NOT NULL,
    ADDRESS TEXT NOT NULL,
    SEQUENCE_NUMBER INTEGER NOT NULL,
    IDENTIFICATION BLOB,
    USER_ID TEXT NOT NULL,
    USER_NAME TEXT,
    PASSWORD TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    EMAIL TEXT,
    OTP TEXT,
    SIGNATURE BLOB,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS MA_COMPANY (
    COMPANY_ID INTEGER NOT NULL,
    COMPANY_NAME TEXT NOT NULL,
    COMPANY_ADDRESS TEXT,
    COMPANY_EMAIL TEXT NOT NULL,
    COMPANY_MOBILE TEXT,
    COMPANY_FAX TEXT,
    ACTIVE_STATUS BOOLEAN,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    COMPANY_LOGO TEXT,
    PRIMARY KEY(COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_ROLES (
    ROLE_ID INTEGER NOT NULL,
    ROLE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MA_AUDIT_ROLES (
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    AUDIT_ROLE_ID INTEGER NOT NULL,
    AUDIT_ROLE_DESC TEXT NOT NULL,
    PRIMARY KEY(COMPANY_ID, AUDIT_ROLE_ID)
);

CREATE TABLE IF NOT EXISTS MA_VESSEL (
    VESSEL_IMO_NO TEXT NOT NULL,
    VESSEL_NAME TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    OFFICIAL_NO INTEGER,
    GRT TEXT,
    COMPANY_IMO_NO TEXT NOT NULL,
    VESSEL_TYPE_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    DATE_OF_REGISTRY TEXT,
    TC_APPROVAL_STATUS TEXT,
    PORT_OF_REGISTRY TEXT,
    VESSEL_PK INTEGER,
    VESSEL_UK INTEGER,
    VESSEL_ID INTEGER,
    CLASS_SOCIETY TEXT,
    CALL_SIGN TEXT,
    VESSEL_STATUS TEXT,
    PRIMARY KEY(VESSEL_IMO_NO, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_VESSEL_TYPE (
    VESSEL_TYPE_ID INTEGER NOT NULL,
    VESSEL_TYPE_NAME TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(VESSEL_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS MA_VESSEL_COMPANY (
    COMPANY_IMO_NO INTEGER NOT NULL,
    DOC_TYPE_NO TEXT,
    DOC_ISSUER TEXT,
    DOC_EXPIRY TEXT,
    COMPANY_ADDRESS TEXT,
    VESSEL_COMPANY_NAME TEXT,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(COMPANY_IMO_NO)
);

CREATE TABLE IF NOT EXISTS AUDIT_DETAILS (
    AUDIT_SEQ_NO TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    VESSEL_IMO_NO TEXT NOT NULL,
    CERTIFICATE_NO INTEGER,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_SUB_TYPE_ID INTEGER NOT NULL,
    COMPANY_IMO_NO TEXT NOT NULL,
    COMPANY_DOC TEXT NOT NULL,
    CERT_EXPIRY_DATE TEXT,
    CERT_ISSUED_DATE TEXT,
    NARRATIVE_SUMMARY BLOB,
    AUDIT_REPORT_NO TEXT NOT NULL,
    AUDIT_DATE TEXT,
    AUDIT_PLACE TEXT,
    AUDIT_STATUS_ID INTEGER,
    CERTIFICATE_ISSUED_ID INTEGER,
    INTERNAL_AUDIT_DATE TEXT,
    OPEN_MEETING_DATE TEXT,
    CLOSE_MEETING_DATE TEXT,
    AUDIT_SUMMARY_ID INTEGER,
    LOCK_STATUS BOOLEAN NOT NULL,
    LOCK_HOLDER TEXT,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    SCOPE INTEGER,
    MAX_STATUS_DATE_CAR TEXT,
    ENDORSE_EXPIRY_DATE TEXT,
    DOC_FLAG INTEGER,
    ALLOW_NEXT INTEGER,
    DOC_TYPE_NUMBER TEXT,
    GRT INTEGER,
    DATE_OF_REGISTRY INTEGER,
    SEAL BLOB,
    TITLE TEXT,
    SIGNATURE BLOB,
    CREDIT_DATE TEXT,
    QID TEXT,
    VESSEL_NAME TEXT,
    VESSEL_TYPE TEXT,
    VESSEL_ADDRESS TEXT,
    DOC_EXPIRY TEXT,
    DOC_ISSUER TEXT,
    DOC_TYPE_NO TEXT,
    CERTIFICATE_VERSION TEXT,
    OFFICIAL_NO TEXT,
    REVIEW_STATUS INTEGER,    /**added by archana for jira ID-Mobile-748*/
    MAKE_FINAL NUMBER,
    PRIMARY KEY(AUDIT_SEQ_NO, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUDIT_TYPE (
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_TYPE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUDIT_SUBTYPE(
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_SUBTYPE_ID INTEGER NOT NULL,
    AUDIT_SUBTYPE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUDIT_SUBTYPE_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUDIT_STATUS (
    AUDIT_STATUS_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_STATUS_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUDIT_STATUS_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_ATTACHMENT_TYPES (
    ATTACHMENT_TYPE_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    ATTACHMENTT_TYPE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    AUDIT_SUB_TYPE_ID INTEGER NOT NULL,
    MANDATORY INTEGER,
    LAST_UPDATED_DATE TEXT NOT NULL,
    PRIMARY KEY(
        ATTACHMENT_TYPE_ID,
        AUDIT_TYPE_ID,
        COMPANY_ID,
        AUDIT_SUB_TYPE_ID
    )
);

CREATE TABLE IF NOT EXISTS MA_CERTIFICATE_ISSUED (
    CERTIFICATE_ISSUE_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    CERTIFICATE_ISSUE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(CERTIFICATE_ISSUE_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_FINDINGS_CATEGORY (
    FINDINGS_CATEGORY_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    FINDINGS_CATEGORY_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(FINDINGS_CATEGORY_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_FINDINGS_STATUS (
    FINDINGS_STATUS_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    FINDINGS_STATUS_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(FINDINGS_STATUS_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUD_OBS_TYPE (
    AUD_OBS_TYPE_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUD_OBS_TYPE_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUD_OBS_TYPE_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUD_OBS_DETAILS (
    AUD_OBS_TYPE_ID INTEGER NOT NULL,
    AUD_OBS_DESC_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUD_OBS_NAME TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    USER_ID TEXT NOT NULL,
    PRIMARY KEY(AUD_OBS_DESC_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS MA_AUDIT_SUMMARY (
    AUD_SUMMARY_ID INTEGER NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUD_SUMMARY_DESC TEXT NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUD_SUMMARY_ID, AUDIT_TYPE_ID, COMPANY_ID)
);

/* CREATE TABLE IF NOT EXISTS MA_AUDIT_SEARCH_SOURCE (AUDIT_SOURCE_ID INTEGER NOT NULL, AUDIT_SOURCE_DESC TEXT NOT NULL, INTEGER NOT NULL, USER_INS TEXT NOT NULL, DATE_INS TEXT NOT NULL, PRIMARY KEY(AUDIT_SOURCE_ID)); */
CREATE TABLE IF NOT EXISTS MA_AUDIT_CODES (
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_CODE TEXT NOT NULL,
    AUDIT_ELEMENTS TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    ACTIVE_STATUS BOOLEAN NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(AUDIT_TYPE_ID, AUDIT_CODE, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS MA_PORT (
    PORT_ID INTEGER NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    PORT_NAME TEXT NOT NULL,
    COUNTRY_NAME TEXT NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    ACTIVE_FLAG INTEGER NOT NULL,
    PRIMARY KEY(COMPANY_ID, PORT_ID)
);

CREATE TABLE IF NOT EXISTS MASTER_TABLE_UPDATE (
    TABLE_NAME TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT,
    DATE_INS TEXT,
    TABLE_UPDATION INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS MA_CERT_ISSUE_REASON (
    COMPANY_ID INTEGER,
    ISSUE_REASON_ID INTEGER,
    ISSUE_REASON_DESC TEXT NOT NULL,
    PRIMARY KEY(COMPANY_ID, ISSUE_REASON_ID)
);

CREATE TABLE IF NOT EXISTS AUDIT_FINDINGS (
    SEQ_NO INTEGER NOT NULL,
    CUR_AUDIT_SEQ_NO INTEGER NOT NULL,
    ORIG_SEQ_NO INTEGER NOT NULL,
    FINDING_NO TEXT NOT NULL,
    AUDIT_DATE TEXT NOT NULL,
    AUDIT_CODE TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    FINDING_STATUS INTEGER,
    DATE_INS TEXT NOT NULL,
    SERIAL_NO TEXT,
    AUDIT_STATUS INTEGER,
    PRIMARY KEY(
        SEQ_NO,
        CUR_AUDIT_SEQ_NO,
        ORIG_SEQ_NO,
        FINDING_NO,
        COMPANY_ID
    )
);
/* "UPDATE_FLAG INTEGER NOT NULL,CHECKBOX_UPDATE INTEGER NOT NULL"  added by archana for jira-id-704,720*/
CREATE TABLE IF NOT EXISTS AUDIT_FINDINGS_DETAILS (
    SEQ_NO INTEGER NOT NULL,
    CUR_AUDIT_SEQ_NO INTEGER NOT NULL,
    ORIG_SEQ_NO INTEGER NOT NULL,
    FINDING_NO TEXT NOT NULL,
    FINDING_SEQ_NO TEXT NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    STATUS_ID INTEGER NOT NULL,
    STATUS_DATE TEXT,
    NEXT_ACTION_ID INTEGER,
    DUE_DATE TEXT,
    DESCRIPTION TEXT,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    AUDIT_TYPE_ID INTEGER,
    UPDATE_DESCRIPTION TEXT,
    AUDIT_PLACE TEXT,
    UPDATE_FLAG INTEGER NOT NULL,    
    CHECKBOX_UPDATE INTEGER NOT NULL,
    PRIMARY KEY(
        SEQ_NO,
        CUR_AUDIT_SEQ_NO,
        ORIG_SEQ_NO,
        FINDING_NO,
        FINDING_SEQ_NO,
        COMPANY_ID
    )
);

CREATE TABLE IF NOT EXISTS AUDIT_FINDING_ATTACHMENTS (
    SEQ_NO INTEGER NOT NULL,
    CUR_AUDIT_SEQ_NO INTEGER NOT NULL,
    ORIG_SEQ_NO INTEGER NOT NULL,
    FINDING_NO TEXT NOT NULL,
    FINDING_SEQ_NO TEXT NOT NULL,
    FILE_SEQ_NO TEXT NOT NULL,
    FILE_NAME TEXT NOT NULL,
    FLAG INTEGER,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    PRIMARY KEY(
        SEQ_NO,
        CUR_AUDIT_SEQ_NO,
        ORIG_SEQ_NO,
        FINDING_NO,
        FINDING_SEQ_NO,
        FILE_SEQ_NO,
        COMPANY_ID
    )
);

CREATE TABLE IF NOT EXISTS AUDIT_AUDITOR_DETAILS (
    AUDIT_SEQ_NO TEXT NOT NULL,
    AUD_OBS_TYPE_ID INTEGER NOT NULL,
    AUD_OBS_ID INTEGER NOT NULL,
    AUDITOR_NAME TEXT NOT NULL,
    AUD_SIGNATURE TEXT,
    AUD_SIGNATURE_DATE TEXT,
    AUD_OBS_LEAD NUMERIC,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    DELEGATE_SIGN NUMBER,
    PRIMARY KEY(
        AUDIT_SEQ_NO,
        AUD_OBS_TYPE_ID,
        AUD_OBS_ID,
        COMPANY_ID
    )
);

CREATE TABLE IF NOT EXISTS AUDIT_REPORT_ATTACHMENTS (
    SEQ_NO INTEGER NOT NULL,
    AUDIT_SEQ_NO TEXT NOT NULL,
    FILE_NAME TEXT,
    ATTACHMENT_TYPE_ID INTEGER,
    COMPANY_ID INTEGER NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS TEXT NOT NULL,
    COMMENTS TEXT NOT NULL,
    OTHER_TYPE TEXT NOT NULL,
    AUDIT_TYPE_ID INTEGER,
    ATTACHMENTT_TYPE_DESC TEXT,
    MANDATORY INTEGER,
    PRIMARY KEY(SEQ_NO, AUDIT_SEQ_NO, COMPANY_ID)
);

/* CREATE TABLE IF NOT EXISTS PDF_DATA_64 (AUDIT_TYPE_ID INTEGER NOT NULL, IMO_NUM INTEGER NOT NULL, AUDIT_SUBTYPE_ID  INTEGER NOT NULL, COMPANY_ID INTEGER NOT NULL, AUDIT_SEQ_NO TEXT NOT NULL, CERTIFICATE_NO TEXT NOT NULL, USER_INS TEXT NOT NULL, DATE_INS TEXT NOT NULL, AUDIT_DATE DATE NOT NULL, PDF_DATA_64 TEXT NOT NULL);*/
CREATE TABLE IF NOT EXISTS SSP_REVIEW_DATA (
    AUDIT_SEQ_NO TEXT NOT NULL,
    AUDIT_TYPE_ID INTEGER,
    COMPANY_ID INTEGER NOT NULL,
    SSP_REPORT_NO TEXT,
    SSP_LEAD_NAME TEXT,
    SSP_REVISION_NO TEXT,
    SSP_DMLC_AUDIT_SEQ_NO INTEGER,
    DUE_DATE TEXT,
    VESSEL_COMPANY_ADDRESS TEXT NOT NULL,
    VESSEL_COMPANY_NAME TEXT NOT NULL,
    OFFICIAL_NO TEXT,
    LTRSTATUS INTEGER,
    DMLC_AUDIT_PLACE TEXT,
    DMLC_ISSUED_DATE TEXT,
    PRIMARY KEY(AUDIT_SEQ_NO, COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS CERTIFICATE_DETAIL (
    AUDIT_SEQ_NO INTEGER NOT NULL,
    COMPANY_ID INTEGER,
    SEQ_NO INTEGER,
    CERTIFICATE_ID INTEGER NOT NULL,
    ENDORSEMENT_ID INTEGER,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    AUDIT_SUB_TYPE_ID INTEGER NOT NULL,
    AUDIT_DATE DATE NOT NULL,
    ENDORSED_DATE DATE,
    AUDIT_PLACE TEXT NOT NULL,
    CERTIFICATE_NO TEXT NOT NULL,
    AUDIT_REPORT_NO TEXT,
    UTN TEXT NOT NULL,
    CERTIFICATE_ISSUE_ID INTEGER NOT NULL,
    QRCODE_URL TEXT NOT NULL,
    CERTIFICATE_VERSION TEXT NOT NULL,
    CERT_ISSUED_DATE DATE NOT NULL,
    CERT_EXPIRY_DATE DATE NOT NULL,
    EXTENDED_ISSUE_DATE DATE,
    EXTENDED_EXPIRY_DATE DATE,
    PUBLISH_STATUS INTEGER NOT NULL,
    ACTIVE_STATUS INTEGER NOT NULL,
    NOTES TEXT,
    LEAD_NAME TEXT,
    ISSUER_ID TEXT NOT NULL,
    ISSUER_NAME TEXT NOT NULL,
    ISSUER_SIGN BLOB,
    ISSUER_SIGN_DATE DATE NOT NULL,
    NAME_TO_PRINT INTEGER NOT NULL,
    SIGN_TO_PRINT INTEGER NOT NULL,
    VERIFY_DONE INTEGER NOT NULL,
    VESSEL_ID INTEGER,
    VESSEL_IMO_NO TEXT NOT NULL,
    VESSEL_NAME TEXT NOT NULL,
    GRT TEXT NOT NULL,
    VESSEL_TYPE TEXT NOT NULL,
    OFFICIAL_NO NUMBER NOT NULL,
    PORT_OF_REGISTRY TEXT NOT NULL,
    DATE_OF_REGISTRY DATE NOT NULL,
    COMPANY_IMO_NO TEXT NOT NULL,
    VESSEL_COMPANY_NAME TEXT NOT NULL,
    VESSEL_COMPANY_ADDRESS TEXT NOT NULL,
    VESSEL_UK TEXT NOT NULL,
    VESSEL_PK TEXT NOT NULL,
    CLASS_SOCIETY TEXT NOT NULL,
    CALL_SIGN TEXT NOT NULL,
    DOC_TYPE_NUMBER TEXT NOT NULL,
    DOC_TYPE TEXT NOT NULL,
    DOC_ISSUER TEXT NOT NULL,
    DOC_EXPIRY DATE NOT NULL,
    USER_INS TEXT NOT NULL,
    DATE_INS DATE NOT NULL,
    TITLE TEXT,
    SEAL TEXT,
    CERTIFICATE_LINK_SEQ NUMBER,
    CONSECTIVE_SUBSEQUENT NUMBER,
    QID TEXT,
    CERT_ORDER_NO NUMBER,
    COMPLETION_DATE DATE,
    DMLCII_ISSUE_DATE TEXT,
    DMLCII_ISSUE_LOCATION TEXT,
    PRIMARY KEY(AUDIT_SEQ_NO, COMPANY_ID, SEQ_NO, AUDIT_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS CERTIFICATE_DETAIL_WITHOUT_AUDIT (
    AUDIT_SEQ_NO INTEGER NOT NULL,
    VESSEL_IMO_NO TEXT NOT NULL,
    AUDIT_TYPE_ID INTEGER NOT NULL,
    CERTIFICATE_ID INTEGER NOT NULL,
    CERTIFICATE_NO TEXT NOT NULL,
    UTN TEXT NOT NULL,
    COMPANY_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS AUDIT_CYCLE (
    ITERATOR INTEGER,
    VESSEL_IMO_NO TEXT,
    VESSEL_ID INTEGER,
    COMPANY_IMO_NO TEXT,
    COMPANY_DOC TEXT,
    DOC_TYPE_NUMBER TEXT,
    AUDIT_TYPE_ID INTEGER,
    AUDIT_SEQ_NO INTEGER,
    CREDIT_DATE DATE,
    NEXT_INTERMEDIATE_START DATE,
    NEXT_INTERMEDIATE_END DATE,
    INTERMEDIATE_DUE_DATE DATE,
    NEXT_RENEWAL_DUE_DATE DATE,
    AUDIT_SUBTYPE_CYCLEGEN INTEGER,
    CYCLE_GEN_NO INTEGER,
    CYCLE_SEQ_NO INTEGER,
    NEXT_RENEWAL_START DATE,
    NEXT_RENEWAL DATE,
    ACTIVE_STATUS INTEGER,
    USER_INS TEXT,
    DATE_INS DATE,
    AUDIT_DATE DATE,
    AUDIT_SUB_TYPE_ID INTEGER,
    LEAD_NAME TEXT,
    ROLE_ID INTEGER,
    USER_ID TEXT,
    SUB_ITERATOR INTEGER
);

CREATE TABLE IF NOT EXISTS LAPTOP_PIN(
   LAP_UNIQUE_ID TEXT, 
   USER_ID TEXT NOT NULL, 
   COMPANY_ID INTEGER NOT NULL, 
   USER_INS TEXT, 
   DATE_INS TEXT, 
   USER_APPROVAL INTEGER NOT NULL,
   MOB_UNIQUE_ID TEXT, 
   PRIMARY KEY(USER_ID,COMPANY_ID)); 
/* CREATE TABLE IF NOT EXISTS USER_DETAILS_CONFIG (OLD_PASSWORD TEXT, NEW_PASSWORD TEXT, CONFIRM_NEW_PASSWORD TEXT, DISPLAY_NAME TEXT, SEARCH_RESULT TEXT, USER_ID TEXT NOT NULL, DEFAULT_HOME_SCREEN TEXT, MANAGER_NAME TEXT, ROLE TEXT, HEADER_COLOUR TEXT, BACKGROUND_COLOUR TEXT, FONT_COLOUR TEXT, BUTTON_COLOUR TEXT, HEADER_FONT_COLOUR TEXT, COMPANY_ID INTEGER NOT NULL, IDENTITY TEXT, EMAIL_ID TEXT NOT NULL, PRIMARY KEY(USER_ID,COMPANY_ID));*/